"""Add timezone field to users

Revision ID: ddf2bf48e522
Revises: 11e834961dde
Create Date: 2025-12-29 22:16:55.647315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf2bf48e522'
down_revision = '11e834961dde'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add timezone column as nullable
    op.add_column('users', sa.Column('timezone', sa.String(), nullable=True))
    # Set default timezone for existing rows
    op.execute("UPDATE users SET timezone = 'America/Los_Angeles' WHERE timezone IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column exists before dropping (handles case where upgrade failed)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('users')]
    if 'timezone' in columns:
        op.drop_column('users', 'timezone')
    # ### end Alembic commands ###

